<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <title>Yaf-Skeleton</title>
    </head>
    <body>
        <pre>
.___        __                             .__    ___________                           
|   | _____/  |_  ___________  ____ _____  |  |   \_   _____/_____________  ___________ 
|   |/    \   __\/ __ \_  __ \/    \\__  \ |  |    |    __)_\_  __ \_  __ \/  _ \_  __ \
|   |   |  \  | \  ___/|  | \/   |  \/ __ \|  |__  |        \|  | \/|  | \(  <_> )  | \/
|___|___|  /__|  \___  >__|  |___|  (____  /____/ /_______  /|__|   |__|   \____/|__|   
         \/          \/           \/     \/               \/                            
        </pre>
    </body>
</html>
 
